### ISSUE TITLE
Langevin bug

### ISSUE THREAD

**Issue by bradenmweight** [bradenmweight/SQD#5]
![image](https://user-images.githubusercontent.com/69997194/213247366-ae997d90-ad2f-4880-8bc5-8f155dda5528.png)

The above figure was generated starting from optimized geometry for the Fullerene molecule (i.e., a Bucky Ball). I subsequently ran NVT dynamics with the current Langevin code for two different friction parameters ("LANGEVIN_LAMBDA") of 1.0 meV and 0.1 meV. As you can see, neither of them are able to keep a consistent temperature of 300 K.

**Comment by bradenmweight** [comment]
`
def do_Langevin_XStep(DYN_PROPERTIES):
    """
    Mark Tuckerman -- Stat. Mech.: Theory and Mol. Simulation
    Chapter 15.5 Page 594 Eq. 15.5.18
    """
    masses  = np.array([ np.array([m,m,m]) for m in DYN_PROPERTIES["MASSES"] ])
    dtI     = DYN_PROPERTIES["dtI"]
    NAtoms  = DYN_PROPERTIES["NAtoms"]
    LANGEVIN_LAMBDA = DYN_PROPERTIES["LANGEVIN_LAMBDA"] / 1000 / 27.2114 # meV --> a.u. # TODO Change units in read_input.py
    TEMP  = DYN_PROPERTIES["TEMP"] * (0.025 / 300) / 27.2114 # K -> KT (a.u.) # TODO Change units in read_input.py

    DYN_PROPERTIES["G_RAND_EPSILON"] = gauss(0,1) # Gaussian random number
    DYN_PROPERTIES["G_RAND_THETA"]   = gauss(0,1) # Gaussian random number

    # Difference in acceleration and damped velocity
    a_ORIG = DYN_PROPERTIES["FORCE_NEW"]/masses  # Original acceleration
    a_DAMP = LANGEVIN_LAMBDA * DYN_PROPERTIES["Atom_velocs_new"] # Acceleration due to damping
    SIGMA = np.sqrt(2 * TEMP * LANGEVIN_LAMBDA / masses) # Gaussian Width
    RANDOM_FAC = 0.5 * DYN_PROPERTIES["G_RAND_EPSILON"] + 1/(2*np.sqrt(3)) * DYN_PROPERTIES["G_RAND_THETA"]

    # A(t) has units of position
    # Store this for VStep without changing.
    DYN_PROPERTIES["LANGEVIN_A"] = 0.5 * dtI**2 * (a_ORIG - a_DAMP) + SIGMA * dtI**(3/2) * RANDOM_FAC
    
    DYN_PROPERTIES["Atom_coords_new"] += dtI * DYN_PROPERTIES["Atom_velocs_new"] + DYN_PROPERTIES["LANGEVIN_A"]

    return DYN_PROPERTIES



def do_Langevin_VStep(DYN_PROPERTIES):
    """
    Mark Tuckerman -- Stat. Mech.: Theory and Mol. Simulation
    Chapter 15.5 Page 594 Eq. 15.5.18
    """
    masses  = np.array([ np.array([m,m,m]) for m in DYN_PROPERTIES["MASSES"] ])
    dtI     = DYN_PROPERTIES["dtI"]
    NAtoms  = DYN_PROPERTIES["NAtoms"]
    LANGEVIN_LAMBDA = DYN_PROPERTIES["LANGEVIN_LAMBDA"] / 1000 / 27.2114 # meV --> a.u. # TODO Change units in read_input.py
    TEMP  = DYN_PROPERTIES["TEMP"] * (0.025 / 300) / 27.2114 # K -> KT (a.u.) # TODO Change units in read_input.py

    SIGMA = np.sqrt(2 * TEMP * LANGEVIN_LAMBDA / masses) # Gaussian Width

    F0 = DYN_PROPERTIES["FORCE_OLD"]
    F1 = DYN_PROPERTIES["FORCE_NEW"]
    LANGEVIN_A = DYN_PROPERTIES["LANGEVIN_A"]

    DYN_PROPERTIES["Atom_velocs_new"] += 0.5000000 * dtI * ( F0 + F1 ) / masses - \
                                         dtI * LANGEVIN_LAMBDA * DYN_PROPERTIES["Atom_velocs_new"] + \
                                         SIGMA * np.sqrt(dtI) * DYN_PROPERTIES["G_RAND_EPSILON"] - \
                                         LANGEVIN_LAMBDA * LANGEVIN_A

    return DYN_PROPERTIES`

**Comment by arkajitmandal** [comment]
the link to the code in question: https://github.com/bradenmweight/SQD/blob/develop/src/NAMD/nuclear_propagation.py

**Comment by bradenmweight** [comment]
![image](https://user-images.githubusercontent.com/69997194/213253387-1aee189e-75b2-4bd2-98b5-52286f9badbb.png)

Here are two additional friction constant calculations: 20 meV and 100 meV.

**Comment by arkajitmandal** [comment]
Looks to me your noise is correlated:

DYN_PROPERTIES["G_RAND_EPSILON"] = gauss(0,1) # Gaussian random number
DYN_PROPERTIES["G_RAND_THETA"]   = gauss(0,1) # Gaussian random number 

note that each DOF will have it own random number

**Comment by bradenmweight** [comment]
Poop -- You are correct, sir. Each DOF needs a new random.

**Comment by bradenmweight** [comment]
Thanks for the keen eyes.

**Comment by bradenmweight** [comment]
![image](https://user-images.githubusercontent.com/69997194/213260863-9af64025-57b2-4e28-9c6d-52e7b9f3ab46.png)

Messy plot, but you can see which one looks good. Purple dots are NVE, blue dots are corrected NVT Langevin with 20 meV friction.
